//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace applicacion.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("applicacion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0c24e52e8e4b8e3d2a0c5fc4c3fb46ac {
            get {
                object obj = ResourceManager.GetObject("0c24e52e8e4b8e3d2a0c5fc4c3fb46ac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0c24e52e8e4b8e3d2a0c5fc4c3fb46ac1 {
            get {
                object obj = ResourceManager.GetObject("0c24e52e8e4b8e3d2a0c5fc4c3fb46ac1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0c24e52e8e4b8e3d2a0c5fc4c3fb46ac2 {
            get {
                object obj = ResourceManager.GetObject("0c24e52e8e4b8e3d2a0c5fc4c3fb46ac2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _234c5602e246db1015651e2510f43311f14cefd7_s2_n3_y1 {
            get {
                object obj = ResourceManager.GetObject("234c5602e246db1015651e2510f43311f14cefd7_s2_n3_y1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _26b3dc82c6146f0e4ef5de0deb25d019 {
            get {
                object obj = ResourceManager.GetObject("26b3dc82c6146f0e4ef5de0deb25d019", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3592827_access_general_house_key_key_lock_key_login_office_107758 {
            get {
                object obj = ResourceManager.GetObject("3592827-access-general-house-key-key-lock-key-login-office_107758", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3592828_general_key_key_lock_lock_office_password_security_107759 {
            get {
                object obj = ResourceManager.GetObject("3592828-general-key-key-lock-lock-office-password-security_107759", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3592855_business_man_employee_general_human_member_office_tie_107745 {
            get {
                object obj = ResourceManager.GetObject("3592855-business-man-employee-general-human-member-office-tie_107745", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3d_illustration_magnifying_glass_png {
            get {
                object obj = ResourceManager.GetObject("3d-illustration-magnifying-glass-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4124804_customize_magnifier_magnifying_lens_options_search_settings_113894 {
            get {
                object obj = ResourceManager.GetObject("4124804-customize-magnifier-magnifying-lens-options-search-settings_113894", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4a1030b1956e3866ec43c78758f9f7182b4970c1_s2_n3_y1 {
            get {
                object obj = ResourceManager.GetObject("4a1030b1956e3866ec43c78758f9f7182b4970c1_s2_n3_y1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4a1030b1956e3866ec43c78758f9f7182b4970c1_s2_n3_y11 {
            get {
                object obj = ResourceManager.GetObject("4a1030b1956e3866ec43c78758f9f7182b4970c1_s2_n3_y11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4a1030b1956e3866ec43c78758f9f7182b4970c1_s2_n3_y12 {
            get {
                object obj = ResourceManager.GetObject("4a1030b1956e3866ec43c78758f9f7182b4970c1_s2_n3_y12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4afc3a3f79a92036da267471bb37a20f {
            get {
                object obj = ResourceManager.GetObject("4afc3a3f79a92036da267471bb37a20f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5db54fd38d531034ca662eb3e484b242de0023c1_s2_n3_y1 {
            get {
                object obj = ResourceManager.GetObject("5db54fd38d531034ca662eb3e484b242de0023c1_s2_n3_y1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6521b6380fd1d56389ad9279cbeefb4a7c7741ba_s2_n3_y11111 {
            get {
                object obj = ResourceManager.GetObject("6521b6380fd1d56389ad9279cbeefb4a7c7741ba_s2_n3_y11111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _736a61b8aacc6c781da9d3400b9578a3 {
            get {
                object obj = ResourceManager.GetObject("736a61b8aacc6c781da9d3400b9578a3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a3dd66eee23adcf2fe0012785f0af287 {
            get {
                object obj = ResourceManager.GetObject("a3dd66eee23adcf2fe0012785f0af287", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ad80f071a1399dc350301f6318df23c2d6d1e3c1_s2_n3_y1 {
            get {
                object obj = ResourceManager.GetObject("ad80f071a1399dc350301f6318df23c2d6d1e3c1_s2_n3_y1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_entrance_exit_internet_log_out_security_icon_127059 {
            get {
                object obj = ResourceManager.GetObject("arrow_entrance_exit_internet_log_out_security_icon_127059", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b201bba98f63a7534ecad762b32bb4eb {
            get {
                object obj = ResourceManager.GetObject("b201bba98f63a7534ecad762b32bb4eb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b8d85083aea8c8e0ef3c5e22b5249ff0 {
            get {
                object obj = ResourceManager.GetObject("b8d85083aea8c8e0ef3c5e22b5249ff0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Casual_Summer {
            get {
                object obj = ResourceManager.GetObject("Casual Summer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crearcuenta {
            get {
                object obj = ResourceManager.GetObject("crearcuenta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap decc2dbc1ae38ce4ece31a8b328cb5babfb9322d_s2_n3_y1 {
            get {
                object obj = ResourceManager.GetObject("decc2dbc1ae38ce4ece31a8b328cb5babfb9322d_s2_n3_y1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_remove_close_icon_181533 {
            get {
                object obj = ResourceManager.GetObject("delete_remove_close_icon_181533", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e58b87144f8cfc88620ada2c0ddc7a73 {
            get {
                object obj = ResourceManager.GetObject("e58b87144f8cfc88620ada2c0ddc7a73", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edcec3237ad70a15c1266773e1eeaf068497f4a9_s2_n3_y1 {
            get {
                object obj = ResourceManager.GetObject("edcec3237ad70a15c1266773e1eeaf068497f4a9_s2_n3_y1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icone_trait_noir {
            get {
                object obj = ResourceManager.GetObject("icone-trait-noir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ingresa_al_sistema {
            get {
                object obj = ResourceManager.GetObject("ingresa al sistema", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap internet_lock_locked_padlock_password_secure_security_icon_127100 {
            get {
                object obj = ResourceManager.GetObject("internet_lock_locked_padlock_password_secure_security_icon_127100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap laptop_1_102326 {
            get {
                object obj = ResourceManager.GetObject("laptop-1_102326", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pen_edit_modify_pencil_icon_181536 {
            get {
                object obj = ResourceManager.GetObject("pen_edit_modify_pencil_icon_181536", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap perrito {
            get {
                object obj = ResourceManager.GetObject("perrito", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus_insert_add_new_icon_181537 {
            get {
                object obj = ResourceManager.GetObject("plus_insert_add_new_icon_181537", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
